### PR TITLE
Add reasons for SvrfErrors and remove useless SvrfErrors

### LINKED ISSUE #64: Errors should provide more context to the developer
# Bug report

## Describe the bug

Errors are not explicit enough for developers to properly debug their situation.

For example, when @jexe made a request with a bad API key he received the response:

```shell
2019-06-11 18:03:24.831603-0400 ARKitFaceFilterDemo[18808:2613663] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x281df0140, domain=1, instance=1>
Authentication Error: There is no token in the server response.
```

Yes, no token was in the response, but the actual issue was that he sent a bad API key.

### Steps to reproduce

1. Use a bad API Key
2. Send request
3. See error `Authentication Error: There is no token in the server response.`

### Expected behavior

A clear error message that tells the developer what is wrong.

A suggestion: We could provide the user with the error message returned from the API.

### Additional context

Discovered by @jexe

### PR DESCRIPTION
**Pull request by AndreiEvstratenko**
## Description

- SvrfErrors updated with messages from a server
- Remove useless SvrfErrors

### Motivation and Context

- closes #64 

### Types of changes

- [ ] Bug fix
- [ ] New feature
- [x] Maintenance

### CODE REVIEW

**Comment by brentchow** [comment]
Why don't you just return the messages provided by the API as suggested in the ticket?

**Comment by AndreiEvstratenko** [comment]
> Why don't you just return the messages provided by the API as suggested in the ticket?

Because we can do it only for `authenticate` function. I'm trying to keep the same style in all functions

**Comment by brentchow** [comment]
@AndreiEvstratenko Why can we only do it for the authentication function? We return descriptive error messages from the API for all endpoints. Here are just a [couple examples](https://docs.svrf.com/docs/error-codes). We also return more descriptive errors that are thrown by services like ElasticSearch, the Express server, etc.

**Comment by AndreiEvstratenko** [comment]
> @AndreiEvstratenko Why can we only do it for the authentication function? We return descriptive error messages from the API for all endpoints. Here are just a [couple examples](https://docs.svrf.com/docs/error-codes). We also return more descriptive errors that are thrown by services like ElasticSearch, the Express server, etc.

updated

**Pull request merged**
