### PR TITLE
Swift 5 support

### LINKED ISSUE #38: [Timebox] Support Swift 5
# Feature request

## Description

With the latest release of Xcode 10.2 (10E125), Swift 5 is now available, would be nice to have support for it.

### PR DESCRIPTION
**Pull request by AndreiEvstratenko**
## Description

- Adding support for [Swift 5](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2)

- If we want to resolve this warning we need to use dependencies with swift 5.0
swift-5-frameworks

There is [Alamofire 5](https://github.com/Alamofire/Alamofire/releases/tag/5.0.0-beta.6) with [Swift 5](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2), but it's `beta`. We need to decide do we need to use this version or not.

- We can see that @jexe already updated [SvrfGLTFSceneKit](https://github.com/Svrf/SvrfGLTFSceneKit) to [Swift 5](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2) in this [commit](https://github.com/Svrf/SvrfGLTFSceneKit/commit/107bc1e4b3025f4a0bd3929c74cbb7135df79faa). We need to publish the new version of [SvrfGLTFSceneKit](https://github.com/Svrf/SvrfGLTFSceneKit).

Steps to finish with supporting [Swift 5](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2) in [SvrfSDK](http://github.com/svrf/svrf-ios-sdk):

- [ ] (optional) Update [Alamofire](https://github.com/Alamofire/Alamofire) to [Alamofire 5](https://github.com/Alamofire/Alamofire/releases/tag/5.0.0-beta.6).
- [x] Publish a new version of [SvrfGLTFSceneKit](https://github.com/Svrf/SvrfGLTFSceneKit) with @jexe's [commit](https://github.com/Svrf/SvrfGLTFSceneKit/commit/107bc1e4b3025f4a0bd3929c74cbb7135df79faa).
- [x] Update [SvrfSDK](http://github.com/svrf/svrf-ios-sdk) with new version of [SvrfGLTFSceneKit](https://github.com/Svrf/SvrfGLTFSceneKit).
- [ ] Merge this PR with updated .podspec file
- [ ] Publish new version of [SvrfSDK](http://github.com/svrf/svrf-ios-sdk) in [CocoaPods](https://cocoapods.org).

cc @brentchow, @ox, @jexe 

### Motivation and Context

- closes #38 

### Screenshots

- language-support-version-podspec
- language-support-version
- language-support-version-tests

### Types of changes

- [ ] Bug fix
- [ ] New feature
- [x] Maintenance

### Checklist

- [x] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by brentchow** [comment]
@AndreiEvstratenko SvrfGLTFSceneKit 1.2.0 with Swift 5 support has been published

**Comment by AndreiEvstratenko** [comment]
> @AndreiEvstratenko SvrfGLTFSceneKit 1.2.0 with Swift 5 support has been published, so you can upgrade it in this PR and bump the version to 2.0.1

Done. What about Alamofire? cc @ox @jexe

**Comment by ox** [comment]
Does the Alamo 5 library work? We're not doing anything wild with networking so maybe it's ok to use the beta?

**Comment by AndreiEvstratenko** [comment]
> Does the Alamo 5 library work? We're not doing anything wild with networking so maybe it's ok to use the beta?

Works well. I tested in another project cc @brentchow @jexe

**Pull request merged**
